# Generated by Django 4.0.6 on 2022-07-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(blank=True, null=True)),
                ('genre_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie_genre',
            },
        ),
        migrations.CreateModel(
            name='MovieKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(blank=True, null=True)),
                ('keyword_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie_keyword',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('adult', models.IntegerField(blank=True, null=True)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('original_language', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=255, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('runtime', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('vote_count', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('popularity', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('count_in_stock', models.IntegerField()),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
