# Generated by Django 4.0.6 on 2022-07-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_movies_numreviews_movies_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='_id',
            field=models.IntegerField(default='000'),
            preserve_default=False,
        ),
    ]
