# Generated by Django 4.0.6 on 2022-07-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_paymentmethod_order_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemsPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
