# Generated by Django 4.0.6 on 2022-07-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_movies__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='_id',
        ),
    ]
