# Generated by Django 4.0.6 on 2022-08-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_movie_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='product',
        ),
    ]
